config/routes.rb
Rails.application.routes.draw do

     root :to => "articles#index"
     resources :articles
resources :comments
get"sign_up" => "user#new", :as => "sign_up"
resources :users
resources :sessions
resources :articles
resources :articles do
    collection { post :import }
  end
resources :articles do
    collection { get :export }
  end

resources :imports do
    collection { post :import }
  end

end

app/models/article.rb
require 'csv'
require 'roo'
require 'spreadsheet'
require 'zip'
# require 'zip/zip'

require 'roo/base'
class Article < ActiveRecord::Base






  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |article|
        csv << article.attributes.values_at(*column_names)
      end
    end
  end





def self.import(file)
  
valid_keys= ["title","content","status"]

total_row = 0
    spreadsheet = open_spreadsheet(file)

    spreadsheet.sheets.each_with_index do |sheet, index|
      spreadsheet.default_sheet = spreadsheet.sheets[index]
# byebug
      header = Array.new
      spreadsheet.row(1).each { |row| header << row.downcase.tr(' ', '_') }
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        data = find_by_id(row["id"]) || new
    data.attributes = row.to_hash.slice(*valid_keys)
    data.save!

      end

end  
end

  




def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when '.csv' then Roo::Csv.new(file.path,csv_options: {encoding: "iso-8859-1:utf-8"})
when '.xls' then Roo::Excel2003XML.new(file.path, nil,  :ignore)
when  '.ods' then Roo::OpenOffice.new(file.path, :password => "password") 
  else raise "Unknown file type: #{file.original_filename}"
  end
end




  has_many :comments, dependent: :destroy

  #       validates :title, presence: true, length: { minimum: 1 }

  #       validates :content, presence: true, length: { minimum: 1 }

  #       validates :status, presence: true

  #       scope :status_active, -> {where(status: 'active')}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

    @articles=Article.all.order(:created_at).page(params[:page]).per(8)
    @comments = Comment.all

    respond_to do |format|
      format.html
      format.csv { send_data Article.to_csv }
      format.xls

    end
  end

  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.csv { send_data Article.to_csv }
      format.xls
    end

  end

  def new
    @article_import = Article.new

  end

  def edit
    @article = Article.find_by_id(params[:id])
  end

  def create

    @article_import = Article.new(params[:article_import])

    if @article_import.save
      redirect_to root_url, notice: "Imported products successfully."
    else
      render :new
    end

  end

  def update

    @article = Article.find_by_id(params[:id])

    if @article.update(params_article)

      flash[:notice] = "Success Update Records"

      redirect_to action: 'index'

    else

      flash[:error] = "data not valid"

      render 'edit'

    end

  end

  def import

    valid_keys= ["id","title","content","created_at","updated_at"]

    total_row = 0
    spreadsheet = Import.open_spreadsheet(params[:file])

    header = Array.new
    spreadsheet.row(1).each { |row| header << row.downcase.tr(' ', '_') }
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
        valid=row.to_hash.slice(*valid_keys)

      data = Article.create(valid)

      spreadsheet.default_sheet= spreadsheet.sheets.last

      header = Array.new
      spreadsheet.row(1).each { |row| header << row.downcase.tr(' ', '_') }
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        data=row.to_hash.slice(*valid_keys)

        comment = Article.last.comments.create(data)

      end
    end

    redirect_to root_url, notice: "Products imported."
  end

  def destroy

    @article = Article.find_by_id(params[:id])

    if @article.destroy

      flash[:notice] = "Success Delete a Records"

      redirect_to action: 'index'

    else

      flash[:error] = "fails delete a records"

      redirect_to action: 'index'

    end

  end

  private

  def params_article
    params.require(:article).permit(:title, :content, :status)

  end

  private

  def change_format
    request.format = "xls"
  end

  def params_comment
    params.require(:comment).permit(:content)

  end

end

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>

        <p>
        <b><%= comment.user.try(:username) %></b>




<%= comment.content %>


        </p>

    <% end %>

app/views/articles/_form.html.erb
           
  <%= form_for @comment, url: comments_path, remote: true do |f| %>
            
            <%= f.hidden_field :article_id, value: @article.id %>
            
            <% if current_user %>
            
            <%= f.hidden_field :user_is, value: current_user.id %>
            
            <% end %>
            
            <br/>

        <div class="form-group">

        <div class="col-sm-8">
        <%= f.text_area :content, cols: 20, rows: 5 ,:class => 'form-control'%>
        </div>
        <br/>
        </div>
        
        
        <div class="form-group">
        <div class="col-offset-sm-2 col-sm-10">
        
        <%= f.submit :submit , :class => 'btn btn-default'%>
        
        
        </div>
        </div>
    <% end %>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off" %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>


<div>

<%= link_to "back to index", articles_path %>

</div>

app/views/articles/index.csv.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="date">Created At</Data></Cell>
        <Cell><Data ss:Type="date">Updated At</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>



      </Row>
    <% @articles.each do |article| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= article.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.content %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.created_at %></Data></Cell>
                <Cell><Data ss:Type="String"><%= article.updated_at %></Data></Cell>
                        <Cell><Data ss:Type="String"><%= article.status %></Data></Cell>



      </Row>
    <% end %>
    </Table>
  </Worksheet>
    <Worksheet ss:Name="Sheet2">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Article ID</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
      </Row>
    <% @comments.each do |comment| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= comment.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.article_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.content %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>



</Workbook>

app/views/articles/index.html.erb
	
	
	
	<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
	<% end %>







	
<h2 style="text-align: center;">Article</h2>

	<div class="container-fluid clearfix">
	<% @articles.each do |article| %>
	<div class="col-sm-3 .hah">
	<div class="box">
	<h4><%= article.title %></h4>
	<p><%= article.content%> 
	</p>
	<%= link_to 'View Detail', article_path(article.id) %>
	

 				<p>	
				<span><%= link_to 'Edit', edit_article_path(article.id) %></span>
				<span>|</span>	
				<span> <%= link_to 'Delete', article_path(article.id), method: "DELETE", data:{confirm: 'Delete this data ? '} %><span>
				</p>		
				</div>
				</div>
				<% end %>
				</p>
				</div>


				<div class="nav navbar-fixed-bottom">
				<div class="row">
		
	<div class="col-sm-3">	
	<%= page_entries_info @articles %>
   </div>
   <div class="col-sm-4">
   		<%= paginate @articles  %>
   </div>


</div>
</div>


	

app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render("articles")) %>");

app/views/articles/index.xls.erb
<?xml version="1.0" encoding="UTF-8"?>

  
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="String">Created At</Data></Cell>
        <Cell><Data ss:Type="String">Updated At</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>



      </Row>
    <% @articles.each do |article| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= article.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.content %></Data></Cell>
        <Cell ><Data ss:Type="dateTime"><%= article.created_at %></Data></Cell>
        <Cell ><Data ss:Type="dateTime"><%= article.updated_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.status %></Data></Cell>



      </Row>
    <% end %>
    </Table>
  </Worksheet>
    <Worksheet ss:Name="Sheet2">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Article ID</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
      </Row>
    <% @comments.each do |comment| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= comment.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.article_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.content %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>



</Workbook>

app/views/articles/index.xlsx.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="date">Created At</Data></Cell>
        <Cell><Data ss:Type="date">Updated At</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>



      </Row>
    <% @articles.each do |article| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= article.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.content %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.created_at %></Data></Cell>
                <Cell><Data ss:Type="String"><%= article.updated_at %></Data></Cell>
                        <Cell><Data ss:Type="String"><%= article.status %></Data></Cell>



      </Row>
    <% end %>
    </Table>
  </Worksheet>
    <Worksheet ss:Name="Sheet2">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Article ID</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
      </Row>
    <% @comments.each do |comment| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= comment.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.article_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.content %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>



</Workbook>

app/views/articles/new.html.erb
<h2>Import Article</h2>
<%= form_tag  import_articles_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/articles/show.html.erb
 
<div class="container" >



	<h3 ><%= @article.title %></h3>
	




	<p><%= @article.content %></p>
	
	<p><%= link_to 'back to index', articles_path %></p>
 


		<h4>Add Comment</h4>
		
		<div id="form-comment">
		
		<%= render 'form' %>
		
		</div>

		
		<div class="clearfix">		</div>


		<h4>Here the comments</h4>
		
		<div id="list-comments">
		
		<%= render 'comments' %>
		
		</div>


</div>






				<div class="nav navbar-fixed-bottom">
				<div class="row">
				<div class="col-sm-2">Download:
	<%= link_to "CSV", article_path(format: "csv") %> |
	<%= link_to "Excel", article_path(format: "xls") %>|
	</div>
	


</div>
</div>

app/views/articles/show.xls.erb
<?xml version="1.0" encoding="UTF-8"?>

  
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
<!--         <Cell><Data ss:Type="String">ID</Data></Cell>
 -->        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
        <Cell><Data ss:Type="String">Created At</Data></Cell>
        <Cell><Data ss:Type="String">Updated At</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>



      </Row>
      <Row>
<!--               <Cell><Data ss:Type="String"><%= @article.id %></Data></Cell>
 -->
        <Cell><Data ss:Type="String"><%= @article.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @article.content %></Data></Cell>
        <Cell ><Data ss:Type="dateTime"><%= @article.created_at %></Data></Cell>
        <Cell ><Data ss:Type="dateTime"><%= @article.updated_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @article.status %></Data></Cell>



      </Row>
    </Table>
  </Worksheet>
    <Worksheet ss:Name="Sheet2">
    <Table>
      <Row>
<!--         <Cell><Data ss:Type="String">ID</Data></Cell>
 -->        <Cell><Data ss:Type="String">Content</Data></Cell>
      </Row>
    <% @comments.each do |comment| %>
      <Row>
<!--         <Cell><Data ss:Type="Number"><%= comment.id %></Data></Cell>
 -->        <Cell><Data ss:Type="String"><%= comment.content %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>



</Workbook>